### ISSUE TITLE
Logic for number in correct spots appears to be off

### ISSUE THREAD

**Issue by jbmcfarlin31** [jbmcfarlin31/python-mastermind#1]
See the following output:
```
What 5 colors would you like to try?: ['r', 'b'] brrrr


You entered brrrr
The correct number in the correct spot was 4
The correct number in the wrong spot was 0


What 5 colors would you like to try?: ['r', 'b'] brrrb


You entered brrrb
The correct number in the correct spot was 5
The correct number in the wrong spot was 0


Congratulations, you won!!!
```

Is this correct?

**Comment by srbrown13** [comment]
If the solution was brrrb then yes.
This says there were two 'b's and three 'r's in the solution

**Comment by srbrown13** [comment]
if you would have tried 'bbrrr' then you would have seen correct number in the wrong spot

**Comment by jbmcfarlin31** [comment]
```
What 5 colors would you like to try?: ['r', 'b'] brrrr

You entered brrrr
The correct number in the correct spot was 4
The correct number in the wrong spot was 0
```
Was correct then? I don't know why, but I thought I would have seen `1` instead of `0` for wrong spot.

**Comment by srbrown13** [comment]
That's a blank line

**Comment by srbrown13** [comment]
I noticed that I did not get a notification from the issue being opened :/

**Comment by srbrown13** [comment]
No there was only three 'r's in the solution and the 'b' was in the correct spot.  All three 'r's were also in the correct spot

**Comment by jbmcfarlin31** [comment]
Okay cool. I was used to seeing correct choices in the wrong spot during testing, until I tried the game for real haha.

**Comment by srbrown13** [comment]
it's a tough game
